name: data_flag_editor
channels:
  - defaults
dependencies:
  - python=3.7
  - ipykernel
  # basics
  - pandas
  # then plot stuff
  - holoviews
  - hvplot
  - panel
  # finally misc 
  - autopep8
  - pip
  - pip: 
    - --no-deps -e . # add editable of this repo to env
